const flagLink = (country) => {
  const countryArray = {
    Afghanistan: 'AF',
    Albania: 'AL',
    Algeria: 'AG',
    'American Samoa': 'AS',
    Andorra: 'AN',
    Angola: 'AO',
    Anguilla: 'AI',
    Antarctica: 'AQ',
    'Antigua and Barbuda': 'AG',
    Argentina: 'AR',
    Armenia: 'AM',
    Aruba: 'AW',
    Australia: 'AU',
    Austria: 'AT',
    Azerbaijan: 'AJ',
    Bahamas: 'BF',
    Bahrain: 'BH',
    Bangladesh: 'BD',
    Barbados: 'BB',
    Belarus: 'BY',
    Belgium: 'BE',
    Belize: 'BH',
    Benin: 'BN',
    Bermuda: 'BM',
    Bhutan: 'BT',
    Bolivia: 'BO',
    'Bosnia and Herzegovina': 'BA',
    Botswana: 'BC',
    'Bouvet Island': 'BV',
    Brazil: 'BR',
    'British Indian Ocean Territory': 'IO',
    Brunei: 'BN',
    Bulgaria: 'BG',
    'Burkina Faso': 'BF',
    Burundi: 'BY',
    Cambodia: 'CB',
    Cameroon: 'CM',
    Canada: 'CA',
    'Cabo Verde': 'CV',
    'Cayman Islands': 'KY',
    'Central African Republic': 'CF',
    Chad: 'TD',
    Chile: 'CI',
    China: 'CN',
    'Christmas Island': 'CX',
    'Cocos (Keeling) Islands': 'CC',
    Colombia: 'CO',
    Comoros: 'CN',
    Congo: 'CG',
    'Congo (Brazzaville)': 'CD',
    'Congo (Kinshasa)': 'CD',
    'Cook Islands': 'CK',
    'Costa Rica': 'CR',
    "Cote D'Ivoire": 'CI',
    Croatia: 'HR',
    Cuba: 'CU',
    Cyprus: 'CY',
    Czechia: 'EZ',
    Denmark: 'DA',
    Djibouti: 'DJ',
    Dominica: 'DO',
    'Dominican Republic': 'DR',
    Ecuador: 'EC',
    Egypt: 'EG',
    'El Salvador': 'SV',
    'Equatorial Guinea': 'GQ',
    Eritrea: 'ER',
    Estonia: 'EE',
    Eswatini: 'WZ',
    Ethiopia: 'ET',
    'Falkland Islands (Malvinas)': 'FK',
    'Faroe Islands': 'FO',
    Fiji: 'FJ',
    Finland: 'FI',
    France: 'FR',
    'French Guiana': 'GF',
    'French Polynesia': 'PF',
    'French Southern Territories': 'TF',
    Gabon: 'GB',
    Gambia: 'GA',
    Georgia: 'GG',
    Germany: 'GM',
    Ghana: 'GH',
    Gibraltar: 'GI',
    Greece: 'GR',
    Greenland: 'GL',
    Grenada: 'GJ',
    Guadeloupe: 'GP',
    Guam: 'GU',
    Guatemala: 'GT',
    Guinea: 'GV',
    'Guinea-Bissau': 'PU',
    Guyana: 'GY',
    Haiti: 'HA',
    'Heard Island and Mcdonald Islands': 'HM',
    'Holy See': 'VT',
    Honduras: 'HO',
    'Hong Kong': 'HK',
    Hungary: 'HU',
    Iceland: 'IS',
    India: 'IN',
    Indonesia: 'ID',
    Iran: 'IR',
    Iraq: 'IZ',
    Ireland: 'EI',
    Israel: 'IS',
    Italy: 'IT',
    Jamaica: 'JM',
    Japan: 'JA',
    Jordan: 'JO',
    Kazakhstan: 'KZ',
    Kenya: 'KE',
    Kiribati: 'KR',
    "Korea, Democratic People's Republic of": 'KP',
    'Korea, South': 'KR',
    Kuwait: 'KU',
    Kyrgyzstan: 'KG',
    Laos: 'LA',
    Latvia: 'LG',
    Lebanon: 'LE',
    Lesotho: 'LT',
    Liberia: 'LI',
    'Libyan Arab Jamahiriya': 'LY',
    Liechtenstein: 'LS',
    Lithuania: 'LH',
    Luxembourg: 'LU',
    Macao: 'MO',
    'Macedonia, the Former Yugoslav Republic of': 'MK',
    Madagascar: 'MG',
    Malawi: 'MI',
    Malaysia: 'MY',
    Maldives: 'MV',
    Mali: 'ML',
    Malta: 'MT',
    'Marshall Islands': 'MH',
    Martinique: 'MQ',
    Mauritania: 'MR',
    Mauritius: 'MP',
    Mayotte: 'YT',
    Mexico: 'MX',
    Micronesia: 'FM',
    Moldova: 'MD',
    Monaco: 'MN',
    Mongolia: 'MG',
    Montenegro: 'MJ',
    Montserrat: 'MS',
    Morocco: 'MO',
    Mozambique: 'MZ',
    Myanmar: 'MM',
    Namibia: 'WA',
    Nauru: 'NR',
    Nepal: 'NP',
    Netherlands: 'NL',
    'Netherlands Antilles': 'AN',
    'New Caledonia': 'NC',
    'New Zealand': 'NZ',
    Nicaragua: 'NU',
    Niger: 'NG',
    Nigeria: 'NI',
    Niue: 'NU',
    'Norfolk Island': 'NF',
    'Northern Mariana Islands': 'MP',
    Norway: 'NO',
    Oman: 'MU',
    Pakistan: 'PK',
    Palau: 'PW',
    'Palestinian Territory, Occupied': 'PS',
    Panama: 'PM',
    'Papua New Guinea': 'PP',
    Paraguay: 'PA',
    Peru: 'PE',
    Philippines: 'RP',
    Pitcairn: 'PN',
    Poland: 'PL',
    Portugal: 'PO',
    'Puerto Rico': 'PR',
    Qatar: 'QA',
    Reunion: 'RE',
    Romania: 'RO',
    Russia: 'RS',
    Rwanda: 'RW',
    'Saint Helena': 'SH',
    'Saint Kitts and Nevis': 'SC',
    'Saint Lucia': 'ST',
    'Saint Pierre and Miquelon': 'PM',
    'Saint Vincent and the Grenadines': 'VC',
    Samoa: 'WS',
    'San Marino': 'SM',
    'Sao Tome and Principe': 'TP',
    'Saudi Arabia': 'SA',
    Senegal: 'SG',
    'Serbia and Montenegro': 'CS',
    Seychelles: 'SC',
    'Sierra Leone': 'SL',
    Singapore: 'SN',
    Slovakia: 'LO',
    Slovenia: 'SI',
    'Solomon Islands': 'SB',
    Somalia: 'SO',
    'South Africa': 'SF',
    'South Georgia and the South Sandwich Islands': 'GS',
    'South Sudan': 'OD',
    Spain: 'SP',
    'Sri Lanka': 'CE',
    Sudan: 'SU',
    Suriname: 'NS',
    'Svalbard and Jan Mayen': 'SJ',
    Swaziland: 'SZ',
    Sweden: 'SW',
    Switzerland: 'SZ',
    Syria: 'SY',
    'Taiwan, Province of China': 'TW',
    Tajikistan: 'TI',
    'Tanzania, United Republic of': 'TZ',
    Thailand: 'TH',
    'Timor-Leste': 'TT',
    'East Timor': 'TL',
    Togo: 'TO',
    Tokelau: 'TK',
    Tonga: 'TO',
    'Trinidad and Tobago': 'TD',
    Tunisia: 'TS',
    Turkey: 'TU',
    Turkmenistan: 'TM',
    'Turks and Caicos Islands': 'TC',
    Tuvalu: 'TV',
    Uganda: 'UG',
    Ukraine: 'UP',
    'United Arab Emirates': 'AE',
    'United Kingdom': 'UK',
    US: 'US',
    'United States Minor Outlying Islands': 'UM',
    Uruguay: 'UY',
    Uzbekistan: 'UZ',
    Vanuatu: 'NH',
    Venezuela: 'VE',
    Vietnam: 'VM',
    'Virgin Islands, British': 'VG',
    'Virgin Islands, U.s.': 'VI',
    'Wallis and Futuna': 'WF',
    Yemen: 'YM',
    Zambia: 'ZA',
    Zimbabwe: 'ZI',
    "Cote d'Ivoire": 'CI',
    Guernsey: 'GG',
    Jersey: 'JE',
    Libya: 'LY',
    'North Macedonia': 'MK',
    Serbia: 'RS',
    Tanzania: 'TZ',
  };

  let ans = 'https://comnplayscience.eu/app/images/notfound.png';

  if (countryArray[country]) {
    ans = `https://www.worldometers.info/img/flags/${countryArray[country]}-flag.gif`;
  }

  return ans;
};

export default flagLink;
